# Generated by Django 3.1.4 on 2020-12-17 01:27

import django.db.models.deletion
import imagekit.models.fields
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='background_img/subject/')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='background_img/unit/')),
                ('desc', models.CharField(default='Description for the unit goes here!', max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SubUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='background_img/subunit/')),
                ('desc', models.CharField(default='Description for the subunit goes here!', max_length=100)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('last_updated', models.DateField()),
                ('content_brief', markdownx.models.MarkdownxField()),
                ('content_summary', models.TextField()),
                ('cheat_sheet', models.TextField()),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='background_img/card/')),
                ('subunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subunit')),
            ],
        ),
    ]
