# Generated by Django 3.1.4 on 2020-12-17 10:55

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='cheat_sheet',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='content_summary',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
