# Generated by Django 3.1.1 on 2020-11-30 00:30

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='content_brief',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='content-brief'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subunit',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
