# Generated by Django 3.1.4 on 2020-12-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_auto_20201204_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='subunit',
            name='desc',
            field=models.CharField(default='Description for the subunit goes here!', max_length=100),
        ),
    ]
