# Generated by Django 3.1.4 on 2020-12-20 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0004_auto_20201219_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(blank=True, max_length=250)),
                ('file', models.FileField(upload_to='related_files/<django.db.models.fields.related.ForeignKey>/')),
                ('flashcard',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_file',
                                   to='main.flashcard')),
            ],
        ),
    ]
