# Generated by Django 3.1.4 on 2020-12-15 09:53

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0004_subunit_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='content_brief',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
