# Generated by Django 3.1.4 on 2020-12-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0005_relatedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatedfile',
            name='flashcard',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='related_file',
            field=models.ManyToManyField(blank=True, to='main.RelatedFile'),
        ),
        migrations.AlterField(
            model_name='relatedfile',
            name='file',
            field=models.FileField(upload_to='related_files/'),
        ),
    ]
