# Generated by Django 3.1.4 on 2020-12-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0006_auto_20201220_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedfile',
            name='file',
            field=models.FilePathField(blank=True),
        ),
    ]
