# Generated by Django 3.1.4 on 2020-12-22 03:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0008_auto_20201221_0640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ('subunit', 'last_updated', 'title')},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='subunit',
            options={'ordering': ('unit', 'title')},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ('subject', 'title')},
        ),
    ]
