# Generated by Django 3.1.4 on 2020-12-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0011_remove_relatedfile_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subunit',
            name='desc',
            field=models.CharField(default='Description for the subunit goes here!', max_length=100,
                                   verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='desc',
            field=models.CharField(default='Description for the unit goes here!', max_length=100,
                                   verbose_name='Description'),
        ),
    ]
